#%RAML 1.0
version: v1
title: SavingsCalculatorAPI
description: Savings plan estimator to calculate growth from compound interest
baseUri: http://build-savingscalculator.us-e2.cloudhub.io/api/
documentation:
  - title: Home
    content: SavingsCalculatorAPI calculates the savings account balance for a fixed interest rate and annual deposits over a number of years.
    
traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string
types:
  balance:
   type: string
   description:  Account balance

/savings:
 is: [client-id-required]
 get:   
  description: Calculate savings growth with annual compounding
  queryParameters:
    deposit:
     type: number
     required: true
     description: Annual deposits
     format: float
     example:
       300
    rate:
     type: number
     required: true
     description: Interest rate
     format: double
     example:
       0.01
    years:
     type: integer
     required: true
     description: Years of saving
     format: int32
     example:
       20
  responses:
    200:
      description: 200 OK
      body:
        application/json:
          type: balance
          example: |
            {
              "balance":"8933.42"
            }
  
       
       





  


  


  
  